// created via code at https://github.com/LukasGrebe/ga-hit-debugger/blob/master/scrape%20measurement%20protocol.md
knownParams = [
  {
    "documentationAnchor": "v",
    "name": "Protocol Version",
    "category": "General",
    "required": true,
    "description": "The Protocol version. The current value is '1'. This will only change when there are changes made that are not backwards compatible.",
    "keyRegex": "^v$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "1",
    "exampleUsage": "v=1"
  },
  {
    "documentationAnchor": "tid",
    "name": "Tracking ID / Web Property ID",
    "category": "General",
    "required": true,
    "description": "The tracking ID / web property ID. The format is UA-XXXX-Y. All collected data is associated by this ID.",
    "keyRegex": "^tid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "UA-XXXX-Y",
    "exampleUsage": "tid=UA-XXXX-Y"
  },
  {
    "documentationAnchor": "aip",
    "name": "Anonymize IP",
    "category": "General",
    "required": false,
    "description": "When present, the IP address of the sender will be anonymized. For example, the IP will be anonymized if any of the following parameters are present in the payload: &aip=, &aip=0, or &aip=1",
    "keyRegex": "^aip$",
    "valueType": "boolean",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "1",
    "exampleUsage": "aip=1"
  },
  {
    "documentationAnchor": "ds",
    "name": "Data Source",
    "category": "General",
    "required": false,
    "description": "Indicates the data source of the hit. Hits sent from analytics.js will have data source set to 'web'; hits sent from one of the mobile SDKs will have data source set to 'app'.",
    "keyRegex": "^ds$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "web",
    "exampleUsage": "ds=web"
  },
  {
    "documentationAnchor": "qt",
    "name": "Queue Time",
    "category": "General",
    "required": false,
    "description": "Used to collect offline / latent hits. The value represents the time delta (in milliseconds) between when the hit being reported occurred and the time the hit was sent. The value must be greater than or equal to 0. Values greater than four hours may lead to hits not being processed.",
    "keyRegex": "^qt$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "560",
    "exampleUsage": "qt=560"
  },
  {
    "documentationAnchor": "z",
    "name": "Cache Buster",
    "category": "General",
    "required": false,
    "description": "Used to send a random number in GET requests to ensure browsers and proxies don't cache hits. It should be sent as the final parameter of the request since we've seen some 3rd party internet filtering software add additional parameters to HTTP requests incorrectly. This value is not used in reporting.",
    "keyRegex": "^z$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "289372387623",
    "exampleUsage": "z=289372387623"
  },
  {
    "documentationAnchor": "cid",
    "name": "Client ID",
    "category": "User",
    "required": false,
    "description": "This field is required if User ID (uid) is not specified in the request. This anonymously identifies a particular user, device, or browser instance. For the web, this is generally stored as a first-party cookie with a two-year expiration. For mobile apps, this is randomly generated for each particular instance of an application install. The value of this field should be a random UUID (version 4) as described in http://www.ietf.org/rfc/rfc4122.txt.",
    "keyRegex": "^cid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "35009a79-1a05-49d7-b876-2b884d0f825b",
    "exampleUsage": "cid=35009a79-1a05-49d7-b876-2b884d0f825b"
  },
  {
    "documentationAnchor": "uid",
    "name": "User ID",
    "category": "User",
    "required": false,
    "description": "This field is required if Client ID (cid) is not specified in the request. This is intended to be a known identifier for a user provided by the site owner/tracking library user. It must not itself be PII (personally identifiable information). The value should never be persisted in GA cookies or other Analytics provided storage.",
    "keyRegex": "^uid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "as8eknlll",
    "exampleUsage": "uid=as8eknlll"
  },
  {
    "documentationAnchor": "sc",
    "name": "Session Control",
    "category": "Session",
    "required": false,
    "description": "Used to control the session duration. A value of 'start' forces a new session to start with this hit and 'end' forces the current session to end with this hit. All other values are ignored.",
    "keyRegex": "^sc$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "start",
    "exampleUsage": "sc=start"
  },
  {
    "documentationAnchor": "uip",
    "name": "IP Override",
    "category": "Session",
    "required": false,
    "description": "The IP address of the user. This should be a valid IP address in IPv4 or IPv6 format. It will always be anonymized just as though &aip (anonymize IP) had been used.",
    "keyRegex": "^uip$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "1.2.3.4",
    "exampleUsage": "uip=1.2.3.4"
  },
  {
    "documentationAnchor": "ua",
    "name": "User Agent Override",
    "category": "Session",
    "required": false,
    "description": "The User Agent of the browser. Note that Google has libraries to identify real user agents. Hand crafting your own agent could break at any time.",
    "keyRegex": "^ua$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14",
    "exampleUsage": "ua=Opera%2F9.80%20%28Windows%20NT%206.0%29%20Presto%2F2.12.388%20Version%2F12.14"
  },
  {
    "documentationAnchor": "geoid",
    "name": "Geographical Override",
    "category": "Session",
    "required": false,
    "description": "The geographical location of the user. The geographical ID should be a two letter country code or a criteria ID representing a city or region (see http://developers.google.com/analytics/devguides/collection/protocol/v1/geoid). This parameter takes precedent over any location derived from IP address, including the IP Override parameter. An invalid code will result in geographical dimensions to be set to '(not set)'.",
    "keyRegex": "^geoid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "US",
    "exampleUsage": "geoid=US"
  },
  {
    "documentationAnchor": "dr",
    "name": "Document Referrer",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies which referral source brought traffic to a website. This value is also used to compute the traffic source. The format of this value is a URL.",
    "keyRegex": "^dr$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "2048 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "http://example.com",
    "exampleUsage": "dr=http%3A%2F%2Fexample.com"
  },
  {
    "documentationAnchor": "cn",
    "name": "Campaign Name",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies the campaign name.",
    "keyRegex": "^cn$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "100 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "(direct)",
    "exampleUsage": "cn=%28direct%29"
  },
  {
    "documentationAnchor": "cs",
    "name": "Campaign Source",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies the campaign source.",
    "keyRegex": "^cs$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "100 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "(direct)",
    "exampleUsage": "cs=%28direct%29"
  },
  {
    "documentationAnchor": "cm",
    "name": "Campaign Medium",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies the campaign medium.",
    "keyRegex": "^cm$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "50 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "organic",
    "exampleUsage": "cm=organic"
  },
  {
    "documentationAnchor": "ck",
    "name": "Campaign Keyword",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies the campaign keyword.",
    "keyRegex": "^ck$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "Blue Shoes",
    "exampleUsage": "ck=Blue%20Shoes"
  },
  {
    "documentationAnchor": "cc",
    "name": "Campaign Content",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies the campaign content.",
    "keyRegex": "^cc$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "content",
    "exampleUsage": "cc=content"
  },
  {
    "documentationAnchor": "ci",
    "name": "Campaign ID",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies the campaign ID.",
    "keyRegex": "^ci$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "100 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "ID",
    "exampleUsage": "ci=ID"
  },
  {
    "documentationAnchor": "gclid",
    "name": "Google AdWords ID",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies the Google AdWords Id.",
    "keyRegex": "^gclid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "CL6Q-OXyqKUCFcgK2goddQuoHg",
    "exampleUsage": "gclid=CL6Q-OXyqKUCFcgK2goddQuoHg"
  },
  {
    "documentationAnchor": "dclid",
    "name": "Google Display Ads ID",
    "category": "Traffic Sources",
    "required": false,
    "description": "Specifies the Google Display Ads Id.",
    "keyRegex": "^dclid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "d_click_id",
    "exampleUsage": "dclid=d_click_id"
  },
  {
    "documentationAnchor": "sr",
    "name": "Screen Resolution",
    "category": "System Info",
    "required": false,
    "description": "Specifies the screen resolution.",
    "keyRegex": "^sr$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "20 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "800x600",
    "exampleUsage": "sr=800x600"
  },
  {
    "documentationAnchor": "vp",
    "name": "Viewport size",
    "category": "System Info",
    "required": false,
    "description": "Specifies the viewable area of the browser / device.",
    "keyRegex": "^vp$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "20 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "123x456",
    "exampleUsage": "vp=123x456"
  },
  {
    "documentationAnchor": "de",
    "name": "Document Encoding",
    "category": "System Info",
    "required": false,
    "description": "Specifies the character set used to encode the page / document.",
    "keyRegex": "^de$",
    "valueType": "text",
    "defaultValue": "UTF-8",
    "maxLength": "20 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "UTF-8",
    "exampleUsage": "de=UTF-8"
  },
  {
    "documentationAnchor": "sd",
    "name": "Screen Colors",
    "category": "System Info",
    "required": false,
    "description": "Specifies the screen color depth.",
    "keyRegex": "^sd$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "20 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "24-bits",
    "exampleUsage": "sd=24-bits"
  },
  {
    "documentationAnchor": "ul",
    "name": "User Language",
    "category": "System Info",
    "required": false,
    "description": "Specifies the language.",
    "keyRegex": "^ul$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "20 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "en-us",
    "exampleUsage": "ul=en-us"
  },
  {
    "documentationAnchor": "je",
    "name": "Java Enabled",
    "category": "System Info",
    "required": false,
    "description": "Specifies whether Java was enabled.",
    "keyRegex": "^je$",
    "valueType": "boolean",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "1",
    "exampleUsage": "je=1"
  },
  {
    "documentationAnchor": "fl",
    "name": "Flash Version",
    "category": "System Info",
    "required": false,
    "description": "Specifies the flash version.",
    "keyRegex": "^fl$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "20 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "10 1 r103",
    "exampleUsage": "fl=10%201%20r103"
  },
  {
    "documentationAnchor": "t",
    "name": "Hit type",
    "category": "Hit",
    "required": true,
    "description": "The type of hit. Must be one of 'pageview', 'screenview', 'event', 'transaction', 'item', 'social', 'exception', 'timing'.",
    "keyRegex": "^t$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "pageview",
    "exampleUsage": "t=pageview"
  },
  {
    "documentationAnchor": "ni",
    "name": "Non-Interaction Hit",
    "category": "Hit",
    "required": false,
    "description": "Specifies that a hit be considered non-interactive.",
    "keyRegex": "^ni$",
    "valueType": "boolean",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "1",
    "exampleUsage": "ni=1"
  },
  {
    "documentationAnchor": "dl",
    "name": "Document location URL",
    "category": "Content Information",
    "required": false,
    "description": "Use this parameter to send the full URL (document location) of the page on which content resides. You can use the &dh and &dp parameters to override the hostname and path + query portions of the document location, accordingly. The JavaScript clients determine this parameter using the concatenation of the document.location.origin + document.location.pathname + document.location.search browser parameters. Be sure to remove any user authentication or other private information from the URL if present. For 'pageview' hits, either &dl or both &dh and &dp have to be specified for the hit to be valid.",
    "keyRegex": "^dl$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "2048 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "http://foo.com/home?a=b",
    "exampleUsage": "dl=http%3A%2F%2Ffoo.com%2Fhome%3Fa%3Db"
  },
  {
    "documentationAnchor": "dh",
    "name": "Document Host Name",
    "category": "Content Information",
    "required": false,
    "description": "Specifies the hostname from which content was hosted.",
    "keyRegex": "^dh$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "100 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "foo.com",
    "exampleUsage": "dh=foo.com"
  },
  {
    "documentationAnchor": "dp",
    "name": "Document Path",
    "category": "Content Information",
    "required": false,
    "description": "The path portion of the page URL. Should begin with '/'. For 'pageview' hits, either &dl or both &dh and &dp have to be specified for the hit to be valid.",
    "keyRegex": "^dp$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "2048 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "/foo",
    "exampleUsage": "dp=%2Ffoo"
  },
  {
    "documentationAnchor": "dt",
    "name": "Document Title",
    "category": "Content Information",
    "required": false,
    "description": "The title of the page / document.",
    "keyRegex": "^dt$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "1500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "Settings",
    "exampleUsage": "dt=Settings"
  },
  {
    "documentationAnchor": "cd",
    "name": "Screen Name",
    "category": "Content Information",
    "required": true,
    "description": "This parameter is optional on web properties, and required on mobile properties for screenview hits, where it is used for the 'Screen Name' of the screenview hit. On web properties this will default to the unique URL of the page by either using the &dl parameter as-is or assembling it from &dh and &dp.",
    "keyRegex": "^cd$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "2048 Bytes",
    "supportedHitTypes": "screenview",
    "exampleValue": "High Scores",
    "exampleUsage": "cd=High%20Scores"
  },
  {
    "documentationAnchor": "cg_",
    "name": "Content Group",
    "category": "Content Information",
    "required": false,
    "description": "Each content group has an associated index. There is a maximum of 10 contents groups. The group index must be a positive integer between 1 and 10, inclusive. The value of a content group is heirarchichal text delimited by '/\" All leading and trailing slashes will be removed and any repeated slashes will be reduced to a single slash. For example, '/a//b/' will be converted to 'a/b'.",
    "keyRegex": "^cg(\\d+)$",
    "keyRegexMatches": [
      "groupIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "100 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "news/sports",
    "exampleUsage": "cg1=news%2Fsports"
  },
  {
    "documentationAnchor": "linkid",
    "name": "Link ID",
    "category": "Content Information",
    "required": false,
    "description": "The ID of a clicked DOM element, used to disambiguate multiple links to the same URL in In-Page Analytics reports when Enhanced Link Attribution is enabled for the property.",
    "keyRegex": "^linkid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "nav_bar",
    "exampleUsage": "linkid=nav_bar"
  },
  {
    "documentationAnchor": "an",
    "name": "Application Name",
    "category": "App Tracking",
    "required": false,
    "description": "Specifies the application name. This field is required for any hit that has app related data (i.e., app version, app ID, or app installer ID). For hits sent to web properties, this field is optional.",
    "keyRegex": "^an$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "100 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "My App",
    "exampleUsage": "an=My%20App"
  },
  {
    "documentationAnchor": "aid",
    "name": "Application ID",
    "category": "App Tracking",
    "required": false,
    "description": "Application identifier.",
    "keyRegex": "^aid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "150 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "com.company.app",
    "exampleUsage": "aid=com.company.app"
  },
  {
    "documentationAnchor": "av",
    "name": "Application Version",
    "category": "App Tracking",
    "required": false,
    "description": "Specifies the application version.",
    "keyRegex": "^av$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "100 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "1.2",
    "exampleUsage": "av=1.2"
  },
  {
    "documentationAnchor": "aiid",
    "name": "Application Installer ID",
    "category": "App Tracking",
    "required": false,
    "description": "Application installer identifier.",
    "keyRegex": "^aiid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "150 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "com.platform.vending",
    "exampleUsage": "aiid=com.platform.vending"
  },
  {
    "documentationAnchor": "ec",
    "name": "Event Category",
    "category": "Event Tracking",
    "required": true,
    "description": "Specifies the event category. Must not be empty.",
    "keyRegex": "^ec$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "150 Bytes",
    "supportedHitTypes": "event",
    "exampleValue": "Category",
    "exampleUsage": "ec=Category"
  },
  {
    "documentationAnchor": "ea",
    "name": "Event Action",
    "category": "Event Tracking",
    "required": true,
    "description": "Specifies the event action. Must not be empty.",
    "keyRegex": "^ea$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "event",
    "exampleValue": "Action",
    "exampleUsage": "ea=Action"
  },
  {
    "documentationAnchor": "el",
    "name": "Event Label",
    "category": "Event Tracking",
    "required": false,
    "description": "Specifies the event label.",
    "keyRegex": "^el$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "event",
    "exampleValue": "Label",
    "exampleUsage": "el=Label"
  },
  {
    "documentationAnchor": "ev",
    "name": "Event Value",
    "category": "Event Tracking",
    "required": false,
    "description": "Specifies the event value. Values must be non-negative.",
    "keyRegex": "^ev$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "event",
    "exampleValue": "55",
    "exampleUsage": "ev=55"
  },
  {
    "documentationAnchor": "ti",
    "name": "Transaction ID",
    "category": "E-Commerce",
    "required": true,
    "description": "A unique identifier for the transaction. This value should be the same for both the Transaction hit and Items hits associated to the particular transaction.",
    "keyRegex": "^ti$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "transaction, item",
    "exampleValue": "OD564",
    "exampleUsage": "ti=OD564"
  },
  {
    "documentationAnchor": "ta",
    "name": "Transaction Affiliation",
    "category": "E-Commerce",
    "required": false,
    "description": "Specifies the affiliation or store name.",
    "keyRegex": "^ta$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "transaction",
    "exampleValue": "Member",
    "exampleUsage": "ta=Member"
  },
  {
    "documentationAnchor": "tr",
    "name": "Transaction Revenue",
    "category": "E-Commerce",
    "required": false,
    "description": "Specifies the total revenue associated with the transaction. This value should include any shipping or tax costs.",
    "keyRegex": "^tr$",
    "valueType": "currency",
    "defaultValue": "0",
    "maxLength": "None",
    "supportedHitTypes": "transaction",
    "exampleValue": "15.47",
    "exampleUsage": "tr=15.47"
  },
  {
    "documentationAnchor": "ts",
    "name": "Transaction Shipping",
    "category": "E-Commerce",
    "required": false,
    "description": "Specifies the total shipping cost of the transaction.",
    "keyRegex": "^ts$",
    "valueType": "currency",
    "defaultValue": "0",
    "maxLength": "None",
    "supportedHitTypes": "transaction",
    "exampleValue": "3.50",
    "exampleUsage": "ts=3.50"
  },
  {
    "documentationAnchor": "tt",
    "name": "Transaction Tax",
    "category": "E-Commerce",
    "required": false,
    "description": "Specifies the total tax of the transaction.",
    "keyRegex": "^tt$",
    "valueType": "currency",
    "defaultValue": "0",
    "maxLength": "None",
    "supportedHitTypes": "transaction",
    "exampleValue": "11.20",
    "exampleUsage": "tt=11.20"
  },
  {
    "documentationAnchor": "in",
    "name": "Item Name",
    "category": "E-Commerce",
    "required": true,
    "description": "Specifies the item name.",
    "keyRegex": "^in$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "item",
    "exampleValue": "Shoe",
    "exampleUsage": "in=Shoe"
  },
  {
    "documentationAnchor": "ip",
    "name": "Item Price",
    "category": "E-Commerce",
    "required": false,
    "description": "Specifies the price for a single item / unit.",
    "keyRegex": "^ip$",
    "valueType": "currency",
    "defaultValue": "0",
    "maxLength": "None",
    "supportedHitTypes": "item",
    "exampleValue": "3.50",
    "exampleUsage": "ip=3.50"
  },
  {
    "documentationAnchor": "iq",
    "name": "Item Quantity",
    "category": "E-Commerce",
    "required": false,
    "description": "Specifies the number of items purchased.",
    "keyRegex": "^iq$",
    "valueType": "integer",
    "defaultValue": "0",
    "maxLength": "None",
    "supportedHitTypes": "item",
    "exampleValue": "4",
    "exampleUsage": "iq=4"
  },
  {
    "documentationAnchor": "ic",
    "name": "Item Code",
    "category": "E-Commerce",
    "required": false,
    "description": "Specifies the SKU or item code.",
    "keyRegex": "^ic$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "item",
    "exampleValue": "SKU47",
    "exampleUsage": "ic=SKU47"
  },
  {
    "documentationAnchor": "iv",
    "name": "Item Category",
    "category": "E-Commerce",
    "required": false,
    "description": "Specifies the category that the item belongs to.",
    "keyRegex": "^iv$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "item",
    "exampleValue": "Blue",
    "exampleUsage": "iv=Blue"
  },
  {
    "documentationAnchor": "pr_id",
    "name": "Product SKU",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The SKU of the product. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)id$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "P12345",
    "exampleUsage": "pr1id=P12345"
  },
  {
    "documentationAnchor": "pr_nm",
    "name": "Product Name",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The name of the product. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)nm$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "Android T-Shirt",
    "exampleUsage": "pr1nm=Android%20T-Shirt"
  },
  {
    "documentationAnchor": "pr_br",
    "name": "Product Brand",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The brand associated with the product. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)br$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "Google",
    "exampleUsage": "pr1br=Google"
  },
  {
    "documentationAnchor": "pr_ca",
    "name": "Product Category",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The category to which the product belongs. Product index must be a positive integer between 1 and 200, inclusive. The product category parameter can be hierarchical. Use / as a delimiter to specify up to 5-levels of hierarchy. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)ca$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "Apparel",
    "exampleUsage": "pr1ca=Apparel"
  },
  {
    "documentationAnchor": "pr_va",
    "name": "Product Variant",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The variant of the product. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)va$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "Black",
    "exampleUsage": "pr1va=Black"
  },
  {
    "documentationAnchor": "pr_pr",
    "name": "Product Price",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The unit price of a product. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)pr$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "currency",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "29.20",
    "exampleUsage": "pr1pr=29.20"
  },
  {
    "documentationAnchor": "pr_qt",
    "name": "Product Quantity",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The quantity of a product. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)qt$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "2",
    "exampleUsage": "pr1qt=2"
  },
  {
    "documentationAnchor": "pr_cc",
    "name": "Product Coupon Code",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The coupon code associated with a product. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)cc$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "SUMMER_SALE13",
    "exampleUsage": "pr1cc=SUMMER_SALE13"
  },
  {
    "documentationAnchor": "pr_ps",
    "name": "Product Position",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The product's position in a list or collection. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)ps$",
    "keyRegexMatches": [
      "productIndex"
    ],
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "2",
    "exampleUsage": "pr1ps=2"
  },
  {
    "documentationAnchor": "pr_cd_",
    "name": "Product Custom Dimension",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "A product-level custom dimension where dimension index is a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)cd(\\d+)$",
    "keyRegexMatches": [
      "productIndex",
      "dimensionIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Member",
    "exampleUsage": "pr1cd2=Member"
  },
  {
    "documentationAnchor": "pr_cm_",
    "name": "Product Custom Metric",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "A product-level custom metric where metric index is a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pr(\\d+)cm(\\d+)$",
    "keyRegexMatches": [
      "productIndex",
      "metricIndex"
    ],
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "28",
    "exampleUsage": "pr1cm2=28"
  },
  {
    "documentationAnchor": "pa",
    "name": "Product Action",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The role of the products included in a hit. If a product action is not specified, all product definitions included with the hit will be ignored. Must be one of: detail, click, add, remove, checkout, checkout_option, purchase, refund. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pa$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "detail",
    "exampleUsage": "pa=detail"
  },
  {
    "documentationAnchor": "ti",
    "name": "Transaction ID",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The transaction ID. This is an additional parameter that can be sent when Product Action is set to 'purchase' or 'refund'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^ti$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "T1234",
    "exampleUsage": "ti=T1234"
  },
  {
    "documentationAnchor": "ta",
    "name": "Affiliation",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The store or affiliation from which this transaction occurred. This is an additional parameter that can be sent when Product Action is set to 'purchase' or 'refund'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^ta$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Google Store",
    "exampleUsage": "ta=Google%20Store"
  },
  {
    "documentationAnchor": "tr",
    "name": "Revenue",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The total value of the transaction, including tax and shipping. If not sent, this value will be automatically calculated using the product quantity and price fields of all products in the same hit. This is an additional parameter that can be sent when Product Action is set to 'purchase' or 'refund'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^tr$",
    "valueType": "currency",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "123.21",
    "exampleUsage": "tr=123.21"
  },
  {
    "documentationAnchor": "tt",
    "name": "Tax",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The total tax associated with the transaction. This is an additional parameter that can be sent when Product Action is set to 'purchase' or 'refund'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^tt$",
    "valueType": "currency",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "10.78",
    "exampleUsage": "tt=10.78"
  },
  {
    "documentationAnchor": "ts",
    "name": "Shipping",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The shipping cost associated with the transaction. This is an additional parameter that can be sent when Product Action is set to 'purchase' or 'refund'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^ts$",
    "valueType": "currency",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "3.55",
    "exampleUsage": "ts=3.55"
  },
  {
    "documentationAnchor": "tcc",
    "name": "Coupon Code",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The transaction coupon redeemed with the transaction. This is an additional parameter that can be sent when Product Action is set to 'purchase' or 'refund'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^tcc$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "SUMMER08",
    "exampleUsage": "tcc=SUMMER08"
  },
  {
    "documentationAnchor": "pal",
    "name": "Product Action List",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The list or collection from which a product action occurred. This is an additional parameter that can be sent when Product Action is set to 'detail' or 'click'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^pal$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Search Results",
    "exampleUsage": "pal=Search%20Results"
  },
  {
    "documentationAnchor": "cos",
    "name": "Checkout Step",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The step number in a checkout funnel. This is an additional parameter that can be sent when Product Action is set to 'checkout'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^cos$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "2",
    "exampleUsage": "cos=2"
  },
  {
    "documentationAnchor": "col",
    "name": "Checkout Step Option",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "Additional information about a checkout step. This is an additional parameter that can be sent when Product Action is set to 'checkout'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^col$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Visa",
    "exampleUsage": "col=Visa"
  },
  {
    "documentationAnchor": "il_nm",
    "name": "Product Impression List Name",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The list or collection to which a product belongs. Impression List index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)nm$",
    "keyRegexMatches": [
      "listIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Search Results",
    "exampleUsage": "il1nm=Search%20Results"
  },
  {
    "documentationAnchor": "il_pi_id",
    "name": "Product Impression SKU",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The product ID or SKU. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)id$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "P67890",
    "exampleUsage": "il1pi2id=P67890"
  },
  {
    "documentationAnchor": "il_pi_nm",
    "name": "Product Impression Name",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The name of the product. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)nm$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Android T-Shirt",
    "exampleUsage": "il1pi2nm=Android%20T-Shirt"
  },
  {
    "documentationAnchor": "il_pi_br",
    "name": "Product Impression Brand",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The brand associated with the product. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)br$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Google",
    "exampleUsage": "il1pi2br=Google"
  },
  {
    "documentationAnchor": "il_pi_ca",
    "name": "Product Impression Category",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The category to which the product belongs. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)ca$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Apparel",
    "exampleUsage": "il1pi2ca=Apparel"
  },
  {
    "documentationAnchor": "il_pi_va",
    "name": "Product Impression Variant",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The variant of the product. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)va$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Black",
    "exampleUsage": "il1pi2va=Black"
  },
  {
    "documentationAnchor": "il_pi_ps",
    "name": "Product Impression Position",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The product's position in a list or collection. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)ps$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex"
    ],
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "2",
    "exampleUsage": "il1pi2ps=2"
  },
  {
    "documentationAnchor": "il_pi_pr",
    "name": "Product Impression Price",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The price of a product. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)pr$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex"
    ],
    "valueType": "currency",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "29.20",
    "exampleUsage": "il1pi2pr=29.20"
  },
  {
    "documentationAnchor": "il_pi_cd_",
    "name": "Product Impression Custom Dimension",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "A product-level custom dimension where dimension index is a positive integer between 1 and 200, inclusive. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)cd(\\d+)$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex",
      "dimensionIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Member",
    "exampleUsage": "il1pi2cd3=Member"
  },
  {
    "documentationAnchor": "il_pi_cm_",
    "name": "Product Impression Custom Metric",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "A product-level custom metric where metric index is a positive integer between 1 and 200, inclusive. Impression List index must be a positive integer between 1 and 200, inclusive. Product index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^il(\\d+)pi(\\d+)cm(\\d+)$",
    "keyRegexMatches": [
      "listIndex",
      "productIndex",
      "metricIndex"
    ],
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "28",
    "exampleUsage": "il1pi2cm3=28"
  },
  {
    "documentationAnchor": "promo_id",
    "name": "Promotion ID",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The promotion ID. Promotion index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^promo(\\d+)id$",
    "keyRegexMatches": [
      "promoIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "SHIP",
    "exampleUsage": "promo1id=SHIP"
  },
  {
    "documentationAnchor": "promo_nm",
    "name": "Promotion Name",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The name of the promotion. Promotion index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^promo(\\d+)nm$",
    "keyRegexMatches": [
      "promoIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Free Shipping",
    "exampleUsage": "promo1nm=Free%20Shipping"
  },
  {
    "documentationAnchor": "promo_cr",
    "name": "Promotion Creative",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The creative associated with the promotion. Promotion index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^promo(\\d+)cr$",
    "keyRegexMatches": [
      "promoIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "Shipping Banner",
    "exampleUsage": "promo1cr=Shipping%20Banner"
  },
  {
    "documentationAnchor": "promo_ps",
    "name": "Promotion Position",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "The position of the creative. Promotion index must be a positive integer between 1 and 200, inclusive. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^promo(\\d+)ps$",
    "keyRegexMatches": [
      "promoIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "banner_slot_1",
    "exampleUsage": "promo1ps=banner_slot_1"
  },
  {
    "documentationAnchor": "promoa",
    "name": "Promotion Action",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "Specifies the role of the promotions included in a hit. If a promotion action is not specified, the default promotion action, 'view', is assumed. To measure a user click on a promotion set this to 'promo_click'. For analytics.js the Enhanced Ecommerce plugin must be installed before using this field.",
    "keyRegex": "^promoa$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "click",
    "exampleUsage": "promoa=click"
  },
  {
    "documentationAnchor": "cu",
    "name": "Currency Code",
    "category": "Enhanced E-Commerce",
    "required": false,
    "description": "When present indicates the local currency for all transaction currency values. Value should be a valid ISO 4217 currency code.",
    "keyRegex": "^cu$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "10 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "EUR",
    "exampleUsage": "cu=EUR"
  },
  {
    "documentationAnchor": "sn",
    "name": "Social Network",
    "category": "Social Interactions",
    "required": true,
    "description": "Specifies the social network, for example Facebook or Google Plus.",
    "keyRegex": "^sn$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "50 Bytes",
    "supportedHitTypes": "social",
    "exampleValue": "facebook",
    "exampleUsage": "sn=facebook"
  },
  {
    "documentationAnchor": "sa",
    "name": "Social Action",
    "category": "Social Interactions",
    "required": true,
    "description": "Specifies the social interaction action. For example on Google Plus when a user clicks the +1 button, the social action is 'plus'.",
    "keyRegex": "^sa$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "50 Bytes",
    "supportedHitTypes": "social",
    "exampleValue": "like",
    "exampleUsage": "sa=like"
  },
  {
    "documentationAnchor": "st",
    "name": "Social Action Target",
    "category": "Social Interactions",
    "required": true,
    "description": "Specifies the target of a social interaction. This value is typically a URL but can be any text.",
    "keyRegex": "^st$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "2048 Bytes",
    "supportedHitTypes": "social",
    "exampleValue": "http://foo.com",
    "exampleUsage": "st=http%3A%2F%2Ffoo.com"
  },
  {
    "documentationAnchor": "utc",
    "name": "User timing category",
    "category": "Timing",
    "required": true,
    "description": "Specifies the user timing category.",
    "keyRegex": "^utc$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "150 Bytes",
    "supportedHitTypes": "timing",
    "exampleValue": "category",
    "exampleUsage": "utc=category"
  },
  {
    "documentationAnchor": "utv",
    "name": "User timing variable name",
    "category": "Timing",
    "required": true,
    "description": "Specifies the user timing variable.",
    "keyRegex": "^utv$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "timing",
    "exampleValue": "lookup",
    "exampleUsage": "utv=lookup"
  },
  {
    "documentationAnchor": "utt",
    "name": "User timing time",
    "category": "Timing",
    "required": true,
    "description": "Specifies the user timing value. The value is in milliseconds.",
    "keyRegex": "^utt$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "123",
    "exampleUsage": "utt=123"
  },
  {
    "documentationAnchor": "utl",
    "name": "User timing label",
    "category": "Timing",
    "required": false,
    "description": "Specifies the user timing label.",
    "keyRegex": "^utl$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "500 Bytes",
    "supportedHitTypes": "timing",
    "exampleValue": "label",
    "exampleUsage": "utl=label"
  },
  {
    "documentationAnchor": "plt",
    "name": "Page Load Time",
    "category": "Timing",
    "required": false,
    "description": "Specifies the time it took for a page to load. The value is in milliseconds.",
    "keyRegex": "^plt$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "3554",
    "exampleUsage": "plt=3554"
  },
  {
    "documentationAnchor": "dns",
    "name": "DNS Time",
    "category": "Timing",
    "required": false,
    "description": "Specifies the time it took to do a DNS lookup.The value is in milliseconds.",
    "keyRegex": "^dns$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "43",
    "exampleUsage": "dns=43"
  },
  {
    "documentationAnchor": "pdt",
    "name": "Page Download Time",
    "category": "Timing",
    "required": false,
    "description": "Specifies the time it took for the page to be downloaded. The value is in milliseconds.",
    "keyRegex": "^pdt$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "500",
    "exampleUsage": "pdt=500"
  },
  {
    "documentationAnchor": "rrt",
    "name": "Redirect Response Time",
    "category": "Timing",
    "required": false,
    "description": "Specifies the time it took for any redirects to happen. The value is in milliseconds.",
    "keyRegex": "^rrt$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "500",
    "exampleUsage": "rrt=500"
  },
  {
    "documentationAnchor": "tcp",
    "name": "TCP Connect Time",
    "category": "Timing",
    "required": false,
    "description": "Specifies the time it took for a TCP connection to be made. The value is in milliseconds.",
    "keyRegex": "^tcp$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "500",
    "exampleUsage": "tcp=500"
  },
  {
    "documentationAnchor": "srt",
    "name": "Server Response Time",
    "category": "Timing",
    "required": false,
    "description": "Specifies the time it took for the server to respond after the connect time. The value is in milliseconds.",
    "keyRegex": "^srt$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "500",
    "exampleUsage": "srt=500"
  },
  {
    "documentationAnchor": "dit",
    "name": "DOM Interactive Time",
    "category": "Timing",
    "required": false,
    "description": "Specifies the time it took for Document.readyState to be 'interactive'. The value is in milliseconds.",
    "keyRegex": "^dit$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "500",
    "exampleUsage": "dit=500"
  },
  {
    "documentationAnchor": "clt",
    "name": "Content Load Time",
    "category": "Timing",
    "required": false,
    "description": "Specifies the time it took for the DOMContentLoaded Event to fire. The value is in milliseconds.",
    "keyRegex": "^clt$",
    "valueType": "integer",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "timing",
    "exampleValue": "500",
    "exampleUsage": "clt=500"
  },
  {
    "documentationAnchor": "exd",
    "name": "Exception Description",
    "category": "Exceptions",
    "required": false,
    "description": "Specifies the description of an exception.",
    "keyRegex": "^exd$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "150 Bytes",
    "supportedHitTypes": "exception",
    "exampleValue": "DatabaseError",
    "exampleUsage": "exd=DatabaseError"
  },
  {
    "documentationAnchor": "exf",
    "name": "Is Exception Fatal?",
    "category": "Exceptions",
    "required": false,
    "description": "Specifies whether the exception was fatal.",
    "keyRegex": "^exf$",
    "valueType": "boolean",
    "defaultValue": "1",
    "maxLength": "None",
    "supportedHitTypes": "exception",
    "exampleValue": "0",
    "exampleUsage": "exf=0"
  },
  {
    "documentationAnchor": "cd_",
    "name": "Custom Dimension",
    "category": "Custom Dimensions / Metrics",
    "required": false,
    "description": "Each custom dimension has an associated index. There is a maximum of 20 custom dimensions (200 for Analytics 360 accounts). The dimension index must be a positive integer between 1 and 200, inclusive.",
    "keyRegex": "^cd(\\d+)$",
    "keyRegexMatches": [
      "dimensionIndex"
    ],
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "150 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "Sports",
    "exampleUsage": "cd1=Sports"
  },
  {
    "documentationAnchor": "cm_",
    "name": "Custom Metric",
    "category": "Custom Dimensions / Metrics",
    "required": false,
    "description": "Each custom metric has an associated index. There is a maximum of 20 custom metrics (200 for Analytics 360 accounts). The metric index must be a positive integer between 1 and 200, inclusive.",
    "keyRegex": "^cm(\\d+)$",
    "keyRegexMatches": [
      "metricIndex"
    ],
    "valueType": "number",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "47",
    "exampleUsage": "cm1=47"
  },
  {
    "documentationAnchor": "xid",
    "name": "Experiment ID",
    "category": "Content Experiments",
    "required": false,
    "description": "This parameter specifies that this user has been exposed to an experiment with the given ID. It should be sent in conjunction with the Experiment Variant parameter.",
    "keyRegex": "^xid$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "40 Bytes",
    "supportedHitTypes": "all",
    "exampleValue": "Qp0gahJ3RAO3DJ18b0XoUQ",
    "exampleUsage": "xid=Qp0gahJ3RAO3DJ18b0XoUQ"
  },
  {
    "documentationAnchor": "xvar",
    "name": "Experiment Variant",
    "category": "Content Experiments",
    "required": false,
    "description": "This parameter specifies that this user has been exposed to a particular variation of an experiment. It should be sent in conjunction with the Experiment ID parameter.",
    "keyRegex": "^xvar$",
    "valueType": "text",
    "defaultValue": "None",
    "maxLength": "None",
    "supportedHitTypes": "all",
    "exampleValue": "1",
    "exampleUsage": "xvar=1"
  }
];
